Mord3rca/gamma-launcher

- launcher/commands/install.py
- setup.py
> Use tenacity to retry download in case of ConnectionError

- README.md
I think my last attempt at this got messed up, but here is a quick and easy venv install guide for this.
Not 100% sure about the Windows commands, I just stole those from python's website.
> Easy python venv install instructions

- setup.py
> Fixing key argument of setup so dependency are installed by pip

- launcher/commands/install.py
> `full-install`: Copy only usefull game files

- launcher/commands/check.py
Just a small thing but the output was a little bit much. Also tidied up the logic a little bit.
I plan to write a global message function for a consistent console output without changing every file.
> Streamline check-md5 output

- launcher/commands/install.py
> Fixing mods with upper case letters in path

- launcher/commands/check.py
Renaming `--redownload` to `--update-cache`.
> `check-md5`: Also download missing files if using `--update-cache`

- launcher/commands/install.py
> Better error message when basic setup is not done correctly

- launcher/commands/check.py
- launcher/commands/install.py
- launcher/commands/tests.py
- launcher/downloader/__init__.py
> More error handling

- launcher/commands/install.py
> Updating mechanism based on remote version

- README.md
Hi, I added two sections under the title Troubleshoot. These are the problems I encountered on my setup (Fedora 39) and how I fixed them to get a working installation.
Many many thanks for creating this launcher and making it possible to play on Linux!
> Add troubleshooting information

- launcher/mods/__init__.py
- launcher/mods/large_file.py
> Large files: Fix path check

- launcher/mods/base.py
> Don't install bin/ dir so it does not conflict with <Anomaly>/bin execs

- launcher/commands/install.py
- launcher/downloader/moddb.py
> Some fixes

- launcher/archive.py
> Replace `system()` by `run([...])` to unsure blocking operation

- launcher/cli.py
- launcher/commands/check.py
- launcher/commands/install.py
- launcher/commands/shader.py
- launcher/commands/tests.py
- launcher/commands/usvfs.py
- setup.py
> Adding configuration file to cache previous command arguments

- README.md
- launcher/archive.py
- setup.py
> Instead of rarfile use unrar

- setup.py
> Force `setuptools` installation if Python >= 3.12

- launcher/mods/__init__.py
- launcher/mods/downloader/github.py
> Fixing archive import

- launcher/commands/install.py
> Add support for custom G.A.M.M.A repository

- launcher/commands/install.py
Update base game to Anomaly 1.5.3 as it's now supported by GAMMA
> update anomaly to 1.5.3

- launcher/commands/check.py
> Fixing `check-md5` command

- launcher/mods/downloader/base.py
- pyproject.toml
> Using `cloudscraper` to mitigate Cloudflare IUAM on ModDB

- launcher/mods/tempfile.py
> Ignore directories when fixing the archive

- launcher/commands/check.py
- launcher/commands/install.py
- launcher/commands/shader.py
- launcher/commands/usvfs.py
> Use `Path.expanduser()` method to support ~ in path

- launcher/commands/install.py
There were multiple reports (my and my friend experienced it too) where `fullscreen` crashed game with fatal error, and thus I wrote this dirt patch.
> user.ltx 'fullscreen' to 'borderless' patch.

- launcher/mods/downloader/base.py
- launcher/mods/downloader/github/git.py
- launcher/mods/downloader/github/legacy.py
> Updating regexp for git downloader & fixing NO_GIT installation

- launcher/mods/archive.py
When file is of unknown type, provide info what happened.
> Detect failed downloads
